### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by HamzaJavaid-gh** [shanface33/AutoSplice_Dataset#1]
Hi! 

Can you share the data link?

**Comment by shanface33** [comment]
Thank you for your interest in our work! We intend to share the dataset link by the end of May, and I will inform you once it becomes available.

**Comment by shanface33** [comment]
Hello, please fill in the following Google form ([link](https://docs.google.com/forms/d/1bHbWZ-DsG1-VKaMs4Puy0996yj485x7HK13fgbNRerE/edit)) to submit your request to AutoSplice dataset. The download link will be sent to you once the form is accepted (in 48 hours). Thank you!
