### ISSUE TITLE
How do you get access to DALL·E?

### ISSUE THREAD

**Issue by EricZhou0221** [shanface33/AutoSplice_Dataset#4]
Do you have a way to deploy DALL·E to a local server?

**Comment by EricZhou0221** [comment]
Thank you for your reply. Is the "DALLE-2 API" you mentioned the link 
![image](https://github.com/shanface33/AutoSplice_Dataset/assets/145949237/b61a1394-4602-4bdf-b127-84612b3f533a)
 provided in the paper?

**Comment by shanface33** [comment]
Yes!
